default:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', 'integration_tests.duckdb') }}"
      schema: "{{ env_var('DBT_DUCKDB_SCHEMA', 'dbt_unittest') }}"
      threads: |
        {{ env_var("DBT_THREADS", 5) }}
