name: Compatibility tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@94527f2e458b27549849d47d273a16bec83a01e9 # v7
        with:
          enable-cache: true
      - name: Run complete compatibility suite
        run: make test-all
      - name: Save logs and artifacts if failed
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: compatibility-test-artifacts
          retention-days: 3
          path: |
            integration_tests/.ci-work/**/logs
            integration_tests/.ci-work/**/target
